name: PyEDGAR
channels:
  - defaults
dependencies:
  - astroid=2.0.4
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - isort=4.3.4
  - lazy-object-proxy=1.3.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - mccabe=0.6.1
  - ncurses=6.1
  - openssl=1.1.1
  - pip=18.1
  - pylint=2.1.1
  - python=3.7.1
  - readline=7.0
  - setuptools=40.5.0
  - six=1.11.0
  - sqlite=3.25.2
  - tk=8.6.8
  - wheel=0.32.2
  - wrapt=1.10.11
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.6.3
    - chardet==3.0.4
    - idna==2.7
    - isodate==0.6.0
    - pyparsing==2.3.0
    - requests==2.20.0
    - urllib3==1.24.1

